export enum ActionTagType {
    Video = "Video",
    Quiz = "Quiz",
    SignIn = "Sign-In",
    Profile = "Profile",
    Social = "Social",
    Invite = "Invite",
    Twitter = "Twitter",
    Link = "Link",
    Blog = "Blog",
    Document = "Document",
    Feedback = "Feedback",
    AirDrop = "AirDrop",
    Trade = "Trade",
    Governance = "Governance",
    Borrow = "Borrow",
    Lend = "Lend",
    Liquidity = "Liquidity",
    Stake = "Stake",
    Mint = "Mint",
    Wallet = "Wallet",
}
